### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by liangxuejingjing** [raphaelsulzer/convolutional_occupancy_networks#1]
Hi， I want to know how to train Convoccnet on new datasets？I do not know how to revise config.py

**Comment by raphaelsulzer** [comment]
Hi and sorry for the late reply,

on which dataset do you want to run ConvONet? Is this a problem related to ConvONet for point clouds with visibility information?

If you structure your dataset the same way as e.g. the ModelNet10 dataset you should only have to make a new config.yaml file. You do not have to change anything in config.py.
