### ISSUE TITLE
Custom dataset training

### ISSUE THREAD

**Issue by hahahahahahahap** [raphaelsulzer/convolutional_occupancy_networks#2]
Hi, thank you for your brilliant work pretty much, and I have starred your work.

I have mesh files in.off format.

And I used sample_mesh.py to extract points.npz and pointcloud.npz.

My question is how do you structure them? My question is how do you structure them? And what I should change in the config.yaml file？

**Comment by raphaelsulzer** [comment]
Hi,

this repository includes a version of Convolutional Occupancy Networks that can processed point clouds with visibility information (see here for more info: https://github.com/raphaelsulzer/dsrv-data).
Your point cloud will not include any visibility information if you use sample_mesh.py to sample your mesh file.

If you are interested in the original Convolutional Occupancy Networks you should ask your question there: https://github.com/autonomousvision/convolutional_occupancy_networks
